export const PLAYERS = {
  gupta: {
    id: "gupta",
    codename: "GUPTA",
    fullName: "Aryan Gupta",
    color: "green",
  },
  gohil: {
    id: "gohil",
    codename: "GOHIL",
    fullName: "Rudra Gohil",
    color: "amber",
  },
};

export const STAGES = [
  {
    id: "temple",
    index: 0,
    codename: "STAGE_01",
    label: "???",
    lat: 51.5398,
    lng: -0.3020,
    radius: 80,
    validation: "photo",
    unlockType: "descriptive",
    gupta: {
      missionTitle: "Permission from Bapuji",
      terminalLines: [
        "Operative GUPTA — activated.",
        "Every protocol needs a blessing.",
        "Report to the white stone palace.",
      ],
      missionBrief: "Jethalal says: 'Naha-dho ke path-puja karke nikalne ka!' Before you trade Alperton for Los Angeles, you need a different kind of routing for your soul. Head to the intricate white stone palace where you can pray that your USC roommates aren't as 'Nonsense' as Pinto was when she failed her own climbing test right in front of us.",
      task: "Stand before the main shrine together. Hands folded, eyes closed. Make a silent wish for the year ahead — LA, the future, all of it. Photo after.",
      clue: "Jethalal says: 'Pehle bhagwan, phir khaana.' Head to the spot where masala chips and cheese are more iconic than Daya and her Garba. Olympic Way knows your order.",
    },
    gohil: {
      missionTitle: "Permission from Bapuji",
      terminalLines: [
        "Operative GOHIL — activated.",
        "All great journeys begin with intention.",
        "Lead the way. You're the Gujarati.",
      ],
      missionBrief: "Even Jethalal knows that without Bapuji's permission, you don't even get tea. Since you're the Gujarati of the group, lead the way to the spot that looks like a high-res Avatar set but feels like home. It's time for a proper darshan — we need all the luck we can get.",
      task: "Stand before the main shrine together. Hands folded, eyes closed. Make a silent wish for the year ahead. Photo after.",
      clue: "Wembley mein ek jagah hai — masala chips aur cheese ka combination itna iconic hai jitna Taarak aur Jethalal ka. Olympic Way. Jao.",
    },
  },
  {
    id: "wembley",
    index: 1,
    codename: "STAGE_02",
    label: "???",
    lat: 51.5560,
    lng: -0.2796,
    radius: 50,
    validation: "photo",
    unlockType: "wordSplit",
    unlockWord: "NAVRATRI",
    gupta: {
      missionTitle: "The Fatakada Break",
      terminalLines: [
        "Wembley sector online...",
        "Masala chips detected...",
        "Cheese confirmed. Proceed.",
      ],
      missionBrief: "Jethalal says: 'Pehle bhagwan, phir khaana.' Head to the spot where masala chips and cheese are more iconic than Daya and her Garba. Marion has already paid.",
      task: "Enjoy Funky Chips — courtesy of Pinto. Take a photo.",
      wordHalf: "NAV",
      clue: "Every October, the car park outside the Arena becomes a different world. Dandiya until midnight, the whole of Gujarat in one postcode. A Delhi boy on the side trying to copy the steps and failing completely. Your half of the unlock word: the prefix of the app that routes you safely home.",
    },
    gohil: {
      missionTitle: "The Fatakada Break",
      terminalLines: [
        "Wembley sector online...",
        "Masala chips detected...",
        "Gujarat represent.",
      ],
      missionBrief: "Masala chips. Cheese. Marion paid. Don't overthink it. Eat. Then move.",
      task: "Enjoy Funky Chips — courtesy of Pinto. Take a photo.",
      wordHalf: "RATRI",
      clue: "Every October at Wembley Arena, you show Gupta what real culture looks like — even if he copies your steps like a glitchy NPC. In the Seven Kingdoms the Long version lasts a lifetime. In Gujarat it's just the second half of your favourite nine-day dance-off. Those five letters are yours.",
    },
  },
  {
    id: "spoons",
    index: 2,
    codename: "STAGE_03",
    label: "???",
    lat: 51.5535255,
    lng: -0.2927701,
    radius: 50,
    validation: "none",
    unlockType: "descriptive",
    gupta: {
      missionTitle: "The Maverick Moon-Landing",
      terminalLines: [
        "High Road sector — online...",
        "Guinness protocol activated...",
        "Sunglasses required. Non-negotiable.",
      ],
      missionBrief: "Remember when you thought you were going to be a high-flying Maverick for Halloween? You returned your flight suit because of a fake AI photo and ended up looking like you were headed to a specific celestial body instead. Go to the spot on the High Road that matches your Astronaut destination.",
      task: "Split the G. Photo proof required.",
      clue: "Royale Leisure Park. Two stops in one. First — a pool table where someone lost every game and learned nothing. Then — reclining seats, David's lecture sacrificed, and a film that did not deserve the effort. Both memories. Same postcode. Western Avenue.",
    },
    gohil: {
      missionTitle: "The Maverick Moon-Landing",
      terminalLines: [
        "J.J. Moon's — sector locked...",
        "Guinness protocol activated...",
        "Your stomach has been through worse.",
      ],
      missionBrief: "In the Seven Kingdoms, the Long version of this brings the White Walkers. Here it just brings cheap Guinness. Look for the initials of a jet pioneer paired with the silent ruler of the night sky. If the floor isn't sticky, you're in the wrong kingdom.",
      task: "Split the G. Photo proof required. Make sure Gupta is wearing his sunglasses.",
      clue: "Royale Leisure Park. Two stops in one. You taught him pool here — he still lost. Then reclining seats, a film that honestly wasn't worth bunking David's class for. Both of them are right there. Western Avenue.",
    },
  },
  {
    id: "tenpin",
    index: 3,
    codename: "STAGE_04",
    label: "???",
    lat: 51.5248,
    lng: -0.2810,
    radius: 60,
    validation: "photo",
    unlockType: "wordSplit",
    unlockWord: "DJIMINI5PRO",
    gupta: {
      missionTitle: "The Royale Rumble",
      terminalLines: [
        "Royale Leisure Park — coordinates locked...",
        "Pool table identified...",
        "GOHIL won everything here. Just so you know.",
      ],
      missionBrief: "Tenpin Acton. GOHIL taught you pool on these very tables. You still lost. He won at everything. Then reclining seats, Now You See Me 3, and a film that did not deserve the lecture you both sacrificed.",
      task: "Enjoy a game of pool. Then — punch machine. Get 800 or above. Photo as proof.",
      wordHalf: "DJI",
      clue: "Every Westfield trip starts as Pinto shopping for clothes and somehow ends with both of you drifting into the same dangerous store. Flying cameras, bad financial decisions, and way too much excitement. Your part is the store/company name — three letters.",
    },
    gohil: {
      missionTitle: "The Royale Rumble",
      terminalLines: [
        "Royale Leisure Park — online...",
        "You won everything here.",
        "The brownie stays between us.",
      ],
      missionBrief: "You taught Pinto pool on these tables. You won every game — obviously. There was also a brownie involved and we are moving on immediately. Then reclining seats, a lecture sacrificed, a film that didn't earn it.",
      task: "Enjoy a game of pool. Then — punch machine. Get 800 or above. Photo as proof.",
      wordHalf: "MINI5PRO",
      clue: "The New York drone may be gone, but the graduation replacement has entered the chat. Dad came through. Your part is the exact compact model name, no spaces.",
    },
  },
  {
    id: "booker",
    index: 4,
    codename: "STAGE_05",
    label: "???",
    lat: 51.5059951,
    lng: -0.2549063,
    radius: 50,
    validation: "photo",
    unlockType: "descriptive",
    gupta: {
      missionTitle: "The Douglas Debacle",
      terminalLines: [
        "Booker Wholesale — sector online...",
        "Supply run initiated...",
        "Locate the evidence. You know what it is.",
      ],
      missionBrief: "Don't expect anything large here — we know your nutty reputation and the specific size of your member according to the group chat. Head to the warehouse where things are bought in bulk, but the snacks are strictly peanut sized.",
      task: "Find a bag of peanuts. Photograph yourself next to them. You know why.",
      clue: "A friend was in trouble once. Wrong place, wrong time, someone else's fault entirely. You got the call and you went — no questions, no hesitation. Shepherd's Bush Road. That building on the corner.",
    },
    gohil: {
      missionTitle: "The Douglas Debacle",
      terminalLines: [
        "Booker Wholesale Acton...",
        "You know this place, GOHIL...",
        "Every aisle. Every shelf. Every memory.",
      ],
      missionBrief: "You know every shelf, every corner, every colleague. There's an aisle here that will remind you of a very specific evening — rice that tasted like a lemon had a personal vendetta, a roommate who meant well, and a 3am stomach ache that lives in infamy.",
      task: "Find the product that made the rice interesting. Photograph it. You know the one.",
      clue: "Jai called. You went. You didn't ask questions. A Sainsbury's delivery, a friend who was somehow already packed and on a flight to India before the dust settled. Every time you pass that building on Shepherd's Bush Road, you think about it.",
    },
  },
  {
    id: "police",
    index: 5,
    codename: "STAGE_06",
    label: "???",
    lat: 51.4946765,
    lng: -0.2243506,
    radius: 60,
    validation: "arrest",
    unlockType: "wordSplit",
    unlockWord: "PANEERBUTTERMASALA",
    gupta: {
      missionTitle: "The Jailbreak",
      terminalLines: [
        "ALERT — OPERATIVE DOWN...",
        "GOHIL has been detained...",
        "Bail authorisation required immediately...",
      ],
      missionBrief: "GOHIL has been arrested. Again. Jai did a runner to India and left him holding the confusion at Sainsbury's. You got the call. You went. No hesitation — same as always. Authorise his release.",
      task: "Authorise bail using the code on your screen. Show it to GOHIL.",
      wordHalf: "PANEER",
      clue: "Bail approved. Next stop is the house where sleepovers became routine, the PS5 worked overtime, and one dish became legendary. Your part is the main ingredient — six letters. The bail code? 230425 — that's 23rd April 2025, the day Marion first properly spoke to both of you.",
    },
    gohil: {
      missionTitle: "The Jailbreak",
      terminalLines: [
        "METROPOLITAN POLICE — BOOKING SYSTEM...",
        "Suspect GOHIL located...",
        "This is not your fault. Mostly.",
      ],
      missionBrief: "Jai really left you holding the bag at Sainsbury's, didn't he? Thank god for Gupta. Stand by the station railings. Look like you're serving time for Jai's heist. GUPTA is arranging bail.",
      task: "Mugshot first. Then recreate the behind-bars photo at the station railings. GUPTA has the bail code — get it from him to complete the release.",
      wordHalf: "BUTTERMASALA",
      clue: "Release granted. Head back to the kitchen where TMKOC played in the background, COD came after, and your signature dish carried the night. Your part is the rest of the dish name, no spaces.",
    },
  },
  {
    id: "isleworth",
    index: 6,
    codename: "STAGE_07",
    label: "???",
    lat: 51.4741,
    lng: -0.336,
    radius: 80,
    validation: "photo",
    unlockType: "descriptive",
    gupta: {
      missionTitle: "The PBM Sanctuary",
      terminalLines: [
        "TW7 6GH — coordinates locked...",
        "Home base identified...",
        "Not your house. But it felt like it.",
      ],
      missionBrief: "TW7. The postcode that felt like home even when it wasn't yours. The kitchen. The paneer butter masala. The nights nobody planned but everyone stayed for. Stand outside. Take the photo.",
      task: "Photo outside the house. Then prank call Rachit — on speaker, together.",
      clue: "SGA treasurer. SASA president. Table tennis trauma. Trini, of all people. Your honour must be restored where the lectures happened and the hub became home. Richmond American University London. Building 12.",
    },
    gohil: {
      missionTitle: "The PBM Sanctuary",
      terminalLines: [
        "Isleworth — TW7 6GH...",
        "Your second home.",
        "The masala is legendary here.",
      ],
      missionBrief: "Teri kitchen. Tera chulha. Paneer butter masala — perfect bana tha. TMKOC on in the background, COD baad mein, aur raat kab gayi pata nahi. TW7 6GH. Ek baar aur.",
      task: "Photo outside. Then prank call Rachit — on speaker, together.",
      clue: "Classrooms, cardboard boxes, Monster cans, security guards with questions, Quant chaos, and the award David still owes you. Time to return to the campus that somehow survived all of it. Richmond American University London. Building 12.",
    },
  },
  {
    id: "raul",
    index: 7,
    codename: "STAGE_08",
    label: "???",
    lat: 51.4613,
    lng: -0.307,
    radius: 60,
    validation: "photo",
    unlockType: "wordSplit",
    unlockWord: "CHECKMATE",
    gupta: {
      missionTitle: "The Legend of Building 12",
      terminalLines: [
        "Richmond American University London — campus online...",
        "RAUL Building 12 — located...",
        "Four years. This is it.",
      ],
      missionBrief: "SGA treasurer. SASA president. Always in the hub or the library while Gohil was winning awards he never got handed to him. You lost to Trini at table tennis in this building. Trini, of all people.",
      task: "Find the table tennis table. Win a game. Photo of the win. Gohil must hold a fake award.",
      wordHalf: "CHECK",
      clue: "Campus cleared, but one memory still has evidence. Remember when you searched every classroom trying to find Gohil, while he and Pinto were hiding in a random one making very questionable academic choices? Your half is the first five letters of the chess warning before the final move.",
    },
    gohil: {
      missionTitle: "The Legend of Building 12",
      terminalLines: [
        "RAUL Building 12 — Richmond American University London...",
        "Four years of BCC Comp Sci...",
        "David still owes you that award.",
      ],
      missionBrief: "There were classrooms in this building that saw more action than the lectures ever did. There was also a cardboard box, a case of Monster, and a security guard who had questions. President of Quant. David never gave you the award. Everyone knows.",
      task: "Find one of the classrooms. You know what you did in them. Complete the classroom challenge — then take a photo. Hold a fake award — claim what David never gave you.",
      wordHalf: "MATE",
      clue: "Four years, one final move. In chess, this is how the game ends when the king is trapped. Your half is the last half of that word — also what Gupta somehow became.",
    },
  },
  {
    id: "richmond",
    index: 8,
    codename: "STAGE_09 — FINAL",
    label: "???",
    lat: 51.444936,
    lng: -0.2947855,
    radius: 60,
    validation: "photo",
    unlockType: "wordSplit",
    unlockWord: "VEERZARA",
    gupta: {
      missionTitle: "The Westward Watch",
      terminalLines: [
        "Final coordinates acquired...",
        "King Henry's Mound — end state...",
        "Protocol complete, GUPTA.",
      ],
      missionBrief: "The views here are better than any 4K monitor in RAUL. This is it. The last stop. St Paul's on the horizon. Bring the drone. LA is waiting for you, Aryan.",
      task: "Final photo — both of you, together, on the Mound.",
      clue: null,
    },
    gohil: {
      missionTitle: "The Westward Watch",
      terminalLines: [
        "King Henry's Mound — final sector...",
        "All stages cleared, GOHIL...",
        "Look at the view.",
      ],
      missionBrief: "The protocol ends here. The deer don't care about your degree. Ronnie would have loved this park. Look toward the horizon — your next chapter begins somewhere over there.",
      task: "Final photo — both of you, together, on the Mound.",
      clue: null,
    },
  },
];
