export const PLAYERS = {
  gupta: {
    id: "gupta",
    codename: "GUPTA",
    fullName: "Aryan Gupta",
    color: "rcb",
    finalMessage: `Gupta,

Lowkey wish you didn’t come back, because saying goodbye a second time will be even harder. Nonetheless, I am very grateful that you did — at least I got my dress, and more importantly, the additional time and memories.

Thank you for being someone I could always go to. I’ve never had to stress knowing you and Gohil were always around to help, whether it was an assignment, help picking out a gift, or just random life advice.

Thank you for adding so much joy and fun to my very boring life. London definitely isn’t the same without you.

I will miss you a lot, fav. I wish only the best for you <3

Lots of love,
Pinto`,
  },
  gohil: {
    id: "gohil",
    codename: "GOHIL",
    fullName: "Rudra Gohil",
    color: "gt",
    finalMessage: `Gohil,

Thank you for being my calm, and for always lifting the weight off my shoulders — whether it was my bag, an assignment, or just life in general. You have this way of making every problem feel smaller, while somehow making my world feel so much bigger. Knowing you were around always made everything feel easier.

Thank you for showing me more of the world than I ever expected. From our first day at the Tower of London to our last day at London Zoo, you’ve taken me to new places, new experiences, new foods, and so many little corners of London I never would have found on my own. You’ve left your mark on this city in the best way, and now everywhere I go reminds me of a memory with you.

Thank you for the help, the support, the laughs, the kisses, the patience, the planning, and, most importantly, the cheese naan.

I love you so much. Richmond would not have been the same without you. As grateful as I am for my degree, you are, without a doubt, the best thing I got from Richmond.

Lots of love,
Pinto ♡`,
  },
};

export const STAGES = [
  {
    id: "temple",
    index: 0,
    codename: "STAGE_01",
    label: "???",
    lat: 51.5398,
    lng: -0.3020,
    radius: 80,
    validation: "photo",
    unlockType: "descriptive",
    gupta: {
      missionTitle: "Permission from Bapuji",
      terminalLines: [
        "Operative GUPTA — activated.",
        "Every protocol needs a blessing.",
        "Report to Shri Sanatan Hindu Mandir.",
      ],
      missionBrief: "Jethalal says: 'Naha-dho ke path-puja karke nikalne ka!' Before the next chapter begins, you need a different kind of routing for your soul. Head to Shri Sanatan Hindu Mandir, where you can pray that your USC roommates aren't as 'Nonsense' as Pinto was when she failed her own climbing test right in front of us.",
      task: "Stand before the main shrine together. Hands folded, eyes closed. Make a silent wish for the year ahead — LA, the future, all of it. Photo after.",
      clue: "Darshan complete. Blessings secured. Your next checkpoint is not in the sky, but it does involve a moon. Follow the High Road to the pub whose name accidentally preserves the memory of one abandoned Maverick costume.",
      completeText: "ROUTE CARD READY · High Road sector unlocked.",
    },
    gohil: {
      missionTitle: "Permission from Bapuji",
      terminalLines: [
        "Operative GOHIL — activated.",
        "All great journeys begin with intention.",
        "Lead the way. You're the Gujarati.",
      ],
      missionBrief: "In true Pinto style, no mission starts without blessings first. Before the chaos, the food, the games, and the questionable decisions, report to the place that looks like it was rendered straight out of Pandora but still feels like home. Darshan first. Side quest later.",
      task: "Stand before the main shrine together. Hands folded, eyes closed. Make a silent wish for the year ahead. Photo after.",
      clue: "Darshan complete. Blessings secured. Pinto protocol now shifts from heaven to High Road: find the place where our date-night tradition lives under a moonlit codename. Strongbow Dark Fruit awaits.",
      completeText: "ROUTE CARD READY · High Road sector unlocked.",
    },
  },
  {
    id: "spoons",
    index: 1,
    codename: "STAGE_02",
    label: "???",
    lat: 51.5535255,
    lng: -0.2927701,
    radius: 50,
    validation: "none",
    unlockType: "descriptive",
    gupta: {
      missionTitle: "The Maverick Moon-Landing",
      terminalLines: [
        "High Road sector — online...",
        "Guinness protocol activated...",
        "Sunglasses required. Non-negotiable.",
      ],
      missionBrief: "High Road sector active. Your next checkpoint is hidden behind a failed Halloween costume, a sticky floor, and the initials of a jet pioneer paired with the ruler of the night sky.",
      task: "Split the G. Photo proof required.",
      clue: "Guinness protocol complete. The moon landing is over; now return to Earth for emergency fuel. Find the Wembley stop where masala chips, cheese, and Pinto-funded damage control are waiting.",
      completeText: "ROUTE CARD READY · Wembley fuel sector unlocked.",
    },
    gohil: {
      missionTitle: "The Maverick Moon-Landing",
      terminalLines: [
        "J.J. Moon's — sector locked...",
        "Guinness protocol activated...",
        "Your stomach has been through worse.",
      ],
      missionBrief: "Go to yours and Pinto's favourite date spot — the one where Strongbow Dark Fruit somehow became tradition. Look for the initials of a jet pioneer paired with the silent ruler of the night sky. If the floor isn't sticky, you're in the wrong kingdom.",
      task: "Split the G. Photo proof required. Make sure Gupta is wearing his sunglasses.",
      clue: "Strongbow protocol complete. Date-night checkpoint cleared. Now guide the team to the Wembley fuel station where masala chips, cheese, and Pinto-funded damage control are waiting.",
      completeText: "ROUTE CARD READY · Wembley fuel sector unlocked.",
    },
  },
  {
    id: "wembley",
    index: 2,
    codename: "STAGE_03",
    label: "???",
    lat: 51.5560,
    lng: -0.2796,
    radius: 50,
    validation: "photo",
    unlockType: "wordSplit",
    unlockWord: "NAVRATRI",
    gupta: {
      missionTitle: "The Fatakada Break",
      terminalLines: [
        "Wembley sector online...",
        "Masala chips detected...",
        "Cheese confirmed. Proceed.",
      ],
      missionBrief: "Jethalal says: 'Pehle bhagwan, phir khaana.' Head to the spot where masala chips and cheese are more iconic than Daya and her Garba. Marion has already paid.",
      task: "Enjoy Funky Chips — courtesy of Pinto. Take a photo.",
      wordHalf: "NAV",
      clue: "Every October, the car park outside the Arena becomes a different world. Dandiya until midnight, the whole of Gujarat in one postcode. A Delhi boy on the side trying to copy the steps and failing completely. Your half of the unlock word: the prefix of the app that routes you safely home.",
    },
    gohil: {
      missionTitle: "The Fatakada Break",
      terminalLines: [
        "Wembley sector online...",
        "Masala chips detected...",
        "Gujarat represent.",
      ],
      missionBrief: "Masala chips. Cheese. Marion paid. Don't overthink it. Eat. Then move.",
      task: "Enjoy Funky Chips — courtesy of Pinto. Take a photo.",
      wordHalf: "RATRI",
      clue: "Every October at Wembley Arena, you show Gupta what real culture looks like — even if he copies your steps like a glitchy NPC. In the Seven Kingdoms the Long version lasts a lifetime. In Gujarat it's just the second half of your favourite nine-day dance-off. Those five letters are yours.",
    },
  },
  {
    id: "tenpin",
    index: 3,
    codename: "STAGE_04",
    label: "???",
    lat: 51.5248,
    lng: -0.2810,
    radius: 60,
    validation: "photo",
    unlockType: "wordSplit",
    unlockWord: "DJIMINI5PRO",
    gupta: {
      missionTitle: "The Royale Rumble",
      terminalLines: [
        "Royale Leisure Park — coordinates locked...",
        "Pool table identified...",
        "GOHIL won everything here. Just so you know.",
      ],
      missionBrief: "Tenpin Acton. GOHIL taught you pool on these very tables. You still lost. He won at everything. Then reclining seats, Now You See Me 3, and a film that did not deserve the lecture you both sacrificed.",
      task: "Enjoy a game of pool. Then — punch machine. Get 800 or above. Photo as proof.",
      wordHalf: "DJI",
      clue: "Every Westfield trip starts as Pinto shopping for clothes and somehow ends with both of you drifting into the same dangerous store. Flying cameras, bad financial decisions, and way too much excitement. Your part is the store/company name — three letters.",
    },
    gohil: {
      missionTitle: "The Royale Rumble",
      terminalLines: [
        "Royale Leisure Park — online...",
        "You won everything here.",
        "The brownie stays between us.",
      ],
      missionBrief: "You taught Pinto pool on these tables. You won every game — obviously. There was also a brownie involved and we are moving on immediately. Then reclining seats, a lecture sacrificed, a film that didn't earn it.",
      task: "Enjoy a game of pool. Then — punch machine. Get 800 or above. Photo as proof.",
      wordHalf: "MINI5PRO",
      clue: "The New York drone may be gone, but the graduation replacement has entered the chat. Dad came through. Your part is the exact compact model name, no spaces.",
    },
  },
  {
    id: "booker",
    index: 4,
    codename: "STAGE_05",
    label: "???",
    lat: 51.5059951,
    lng: -0.2549063,
    radius: 50,
    validation: "photo",
    unlockType: "descriptive",
    gupta: {
      missionTitle: "The Douglas Debacle",
      terminalLines: [
        "Booker Wholesale — sector online...",
        "Supply run initiated...",
        "Locate the evidence. You know what it is.",
      ],
      missionBrief: "Don't expect anything large here — we know your nutty reputation and the specific size of your member according to the group chat. Head to the warehouse where things are bought in bulk, but the snacks are strictly peanut sized.",
      task: "Booker supply run. Find the tiny salted survival ration from the Lichfield files. It weighs less than your ego after a table-tennis loss. Enter its Booker product code, then take the evidence photo.",
      clue: "A friend was in trouble once. Wrong place, wrong time, someone else's fault entirely. You got the call and you went — no questions, no hesitation. Shepherd's Bush Road. That building on the corner.",
    },
    gohil: {
      missionTitle: "The Douglas Debacle",
      terminalLines: [
        "Booker Wholesale Acton...",
        "You know this place, GOHIL...",
        "Every aisle. Every shelf. Every memory.",
      ],
      missionBrief: "You know every shelf, every corner, every colleague. But this one goes back further than Booker: first-date protocol, Tower of London, and the Kohinoor — one priceless stone.",
      task: "Find the limescale remover — the Booker weapon against the unwanted stones hiding in kettles. Enter its Booker product code, then take the evidence photo.",
      clue: "Jai called. You went. You didn't ask questions. A Sainsbury's delivery, a friend who was somehow already packed and on a flight to India before the dust settled. Every time you pass that building on Shepherd's Bush Road, you think about it.",
    },
  },
  {
    id: "police",
    index: 5,
    codename: "STAGE_06",
    label: "???",
    lat: 51.4946765,
    lng: -0.2243506,
    radius: 60,
    validation: "arrest",
    unlockType: "wordSplit",
    unlockWord: "PANEERCHEESEBUTTER",
    gupta: {
      missionTitle: "The Jailbreak",
      terminalLines: [
        "ALERT — OPERATIVE DOWN...",
        "GOHIL has been detained...",
        "Bail authorisation required immediately...",
      ],
      missionBrief: "GOHIL has been arrested. Again. Jai did a runner to India and left him holding the confusion at Sainsbury's. You got the call. You went. No hesitation — same as always. Authorise his release.",
      task: "Authorise bail using the code on your screen. Show it to GOHIL.",
      wordHalf: "PANEER",
      clue: "Bail approved. Next stop is the house where sleepovers became routine, the PS5 worked overtime, and one dish somehow became part of the lore. Your fragment is the thing that started the whole order.",
    },
    gohil: {
      missionTitle: "The Jailbreak",
      terminalLines: [
        "METROPOLITAN POLICE — BOOKING SYSTEM...",
        "Suspect GOHIL located...",
        "This is not your fault. Mostly.",
      ],
      missionBrief: "Jai really left you holding the bag at Sainsbury's, didn't he? Thank god for Gupta. Stand by the station railings. Look like you're serving time for Jai's heist. GUPTA is arranging bail.",
      task: "Mugshot first. Then recreate the behind-bars photo at the station railings. GUPTA has the bail code — get it from him to complete the release.",
      wordHalf: "CHEESEBUTTER",
      clue: "Release granted. Head back to the kitchen where TMKOC played in the background, COD came after, and your signature order carried the night. Your fragment completes what Gupta starts.",
    },
  },
  {
    id: "isleworth",
    index: 6,
    codename: "STAGE_07",
    label: "???",
    lat: 51.4741,
    lng: -0.336,
    radius: 80,
    validation: "photo",
    unlockType: "descriptive",
    gupta: {
      missionTitle: "The PBM Sanctuary",
      terminalLines: [
        "TW7 6GH — coordinates locked...",
        "Home base identified...",
        "Not your house. But it felt like it.",
      ],
      missionBrief: "TW7. The postcode that felt like home even when it wasn't yours. Aryan's kitchen, the legendary dinner, TMKOC in the background, COD after, and the kind of night nobody planned but everyone stayed for. Stand outside. Take the photo.",
      task: "Photo outside the house. Then prank call Rachit — on speaker, together.",
      clue: "SGA treasurer. SASA president. Table tennis trauma. Trini, of all people. Your honour must be restored where the lectures happened and the hub became home.",
    },
    gohil: {
      missionTitle: "The PBM Sanctuary",
      terminalLines: [
        "Isleworth — TW7 6GH...",
        "Your second home.",
        "The masala is legendary here.",
      ],
      missionBrief: "Aryan's kitchen. Aryan ka chulha. The dish was perfect, TMKOC on in the background, COD baad mein, aur raat kab gayi pata nahi. TW7 6GH. Ek baar aur.",
      task: "Photo outside. Then prank call Rachit — on speaker, together.",
      clue: "Classrooms, cardboard boxes, Starbucks coffees, security guards with questions, Quant chaos, and the award David still owes you. Time to return to the campus that somehow survived all of it.",
    },
  },
  {
    id: "raul",
    index: 7,
    codename: "STAGE_08",
    label: "???",
    lat: 51.4613,
    lng: -0.307,
    radius: 60,
    validation: "photo",
    unlockType: "wordSplit",
    unlockWord: "CHECKMATE",
    gupta: {
      missionTitle: "The Legend of Building 12",
      terminalLines: [
        "Richmond American University London — campus online...",
        "RAUL Building 12 — located...",
        "Four years. This is it.",
      ],
      missionBrief: "SGA treasurer. SASA president. Always in the hub or the library while Gohil was collecting honours he still somehow never got handed properly. Before the campus trail continues, settle one final RAUL score: Gupta versus Gohil.",
      task: "Find the table tennis table. Gupta plays the match against Gohil. Win, lose, or get humbled — photo proof after.",
      wordHalf: "CHECK",
      clue: "Match complete. Gohil has the next hint. Your half is the warning a king receives when the board starts closing in.",
    },
    gohil: {
      missionTitle: "The Legend of Building 12",
      terminalLines: [
        "RAUL Building 12 — Richmond American University London...",
        "Four years of BSc Comp Sci...",
        "David still owes you that award.",
      ],
      missionBrief: "There were classrooms in this building that saw more action than the lectures ever did. There was also a cardboard box, a Starbucks coffee, a security guard who had questions, and one Math Award David still owes you. After the match, the real trail begins.",
      task: "After Gupta plays the match with you, look for the hearts hidden around the classrooms. Follow the heart trail carefully — it leads to your Math Award. Photo proof when you find it.",
      wordHalf: "MATE",
      clue: "The hearts have the route. Follow them through the classrooms and claim the award waiting at the end. Your half is the ending move: when the king has nowhere left to run — and somehow, what Gupta became.",
    },
  },
  {
    id: "richmond",
    index: 8,
    codename: "STAGE_09 — FINAL",
    label: "???",
    lat: 51.444936,
    lng: -0.2947855,
    radius: 60,
    validation: "photo",
    unlockType: "wordSplit",
    unlockWord: "CUMLAUDE",
    gupta: {
      missionTitle: "The Westward Watch",
      terminalLines: [
        "Final coordinates acquired...",
        "Pembroke Lodge — end state...",
        "Protocol complete, GUPTA.",
      ],
      missionBrief: "The views here are better than any 4K monitor in RAUL. This is it. The last stop. St Paul's on the horizon. Bring the drone. LA is waiting for you, Aryan.",
      task: "Final photo — both of you, together, on the Mound.",
      wordHalf: "CUM",
      clue: "Final honour protocol unlocked. Your fragment looks deeply unserious on its own, but in the right academic context it becomes respectable. Take the opening fragment of the honour Pinto has been flexing all week.",
    },
    gohil: {
      missionTitle: "The Westward Watch",
      terminalLines: [
        "Pembroke Lodge — final sector...",
        "All stages cleared, GOHIL...",
        "Look at the view.",
      ],
      missionBrief: "The protocol ends here. The deer don't care about your degree. Ronnie would have loved this park. Look toward the horizon — your next chapter begins somewhere over there.",
      task: "Final photo — both of you, together, on the Mound.",
      wordHalf: "LAUDE",
      clue: "Your fragment sounds like something your Gujarati/Hindi-speaking friends should absolutely not be shouting in Pembroke Lodge. In the right academic context, it completes Pinto's final honour. Take the ending fragment.",
    },
  },
];
