export const STAGES = [
  {
    id: "wembley",
    index: 0,
    codename: "STAGE_01",
    label: "Funky Chips Wembley",
    missionBrief: "Operative, your first objective: acquire sustenance at the designated chip establishment. Pre-payment confirmed. No transaction required.",
    lat: 51.5560,
    lng: -0.2796,
    radius: 50,
    validation: "voucher",
    voucherTitle: "MEAL VOUCHER — FUNKY CHIPS",
    voucherCode: "GRAD-CHIPS-2024",
    passcode: null,
    terminalLines: [
      "Scanning Wembley sector...",
      "Locating fried-potato facility...",
      "Pre-payment verified. Standing by...",
    ],
  },
  {
    id: "spoons",
    index: 1,
    codename: "STAGE_02",
    label: "J.J. Moon's (Wetherspoons)",
    missionBrief: "Proceed to the designated public house. A passcode has been left at the venue. Find it. Enter it. Move on.",
    lat: 51.5602,
    lng: -0.3019,
    radius: 50,
    validation: "passcode",
    passcode: "LLBW",
    terminalLines: [
      "Detecting Wetherspoon coordinates...",
      "Cross-referencing pub database...",
      "Passcode awaiting input...",
    ],
  },
  {
    id: "police",
    index: 2,
    codename: "STAGE_03",
    label: "Hammersmith Police Station",
    missionBrief: "You have been flagged in our system. Report to the station immediately. A mugshot is required for processing.",
    lat: 51.4927,
    lng: -0.2254,
    radius: 50,
    validation: "mugshot",
    passcode: null,
    terminalLines: [
      "INTERPOL DATABASE ACCESSED...",
      "Suspect profile located...",
      "Mugshot capture required...",
    ],
  },
  {
    id: "booker",
    index: 3,
    codename: "STAGE_04",
    label: "Booker Wholesale Acton",
    missionBrief: "A supply run. Your handler has left a passcode on the premises. Extract it without arousing suspicion.",
    lat: 51.5074,
    lng: -0.2674,
    radius: 50,
    validation: "passcode",
    passcode: "BULK47",
    terminalLines: [
      "Accessing Booker logistics grid...",
      "Warehouse sector scan initiated...",
      "Agent, locate the passcode...",
    ],
  },
  {
    id: "isleworth",
    index: 4,
    codename: "STAGE_05",
    label: "Isleworth (TW7 6GH)",
    missionBrief: "Arrive at the designated residential coordinates. Photograph the target location as proof of presence.",
    lat: 51.4741,
    lng: -0.3360,
    radius: 50,
    validation: "photo",
    passcode: null,
    terminalLines: [
      "Triangulating TW7 coordinates...",
      "Residential sector identified...",
      "Photo documentation required...",
    ],
  },
  {
    id: "raul",
    index: 5,
    codename: "STAGE_06",
    label: "RAUL Building 12",
    missionBrief: "Infiltrate the RAUL facility. A contact has left a passcode at Building 12. Retrieve it.",
    lat: 51.4613,
    lng: -0.3070,
    radius: 50,
    validation: "passcode",
    passcode: "RAUL12X",
    terminalLines: [
      "RAUL campus grid loading...",
      "Building 12 located...",
      "Await passcode transmission...",
    ],
  },
  {
    id: "pembroke",
    index: 6,
    codename: "STAGE_07",
    label: "Pembroke Lodge (Ice Cream)",
    missionBrief: "You've earned it. Proceed to the ice cream station. Voucher active upon arrival. Aryan's orders.",
    lat: 51.4455,
    lng: -0.2958,
    radius: 50,
    validation: "voucher",
    voucherTitle: "ICE CREAM VOUCHER — PEMBROKE LODGE",
    voucherCode: "GRAD-ICECREAM-2024",
    terminalLines: [
      "Richmond Park sector — online...",
      "Pembroke Lodge GPS lock confirmed...",
      "Sweet reward protocol activated...",
    ],
  },
  {
    id: "richmond",
    index: 7,
    codename: "STAGE_08 — FINAL",
    label: "King Henry's Mound",
    missionBrief: "This is it. The final destination. Reach King Henry's Mound and complete the Protocol. The view is your reward.",
    lat: 51.4471,
    lng: -0.3021,
    radius: 50,
    validation: "photo",
    passcode: null,
    terminalLines: [
      "Final coordinates acquired...",
      "Protocol end-state approaching...",
      "Complete the mission, Operative...",
    ],
  },
];
